web:
  build: .
  command: 'bash -c ''bundle exec puma -C config/puma.rb'''
  env_file: '.env'
  working_dir: /app/user
  env_file: '.env'
  environment:
    RAILS_ENV:
    PORT: 8080
#    DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres'
  ports:
    - '8080:8080'
  links:
    - herokuPostgresql
  volumes:
    - '.:/app/user'
  tty: true
  stdin_open: true
shell:
  build: .
  command: bash
  working_dir: /app/user
  env_file: '.env'
  environment:
    RAILS_ENV:
    PORT: 8080
  ports:
    - '8080:8080'
  links:
    - herokuPostgresql
  volumes:
    - '.:/app/user'
herokuPostgresql:
  image: postgres
